### ISSUE TITLE
PostgreSQL storage provider

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/globalstorage#137] opened 2018-07-30 20:52 UTC

**Comment by nechaido** [comment] 2018-08-01 16:16
@tshemsedinov I have a few questions:
* should we provide API for creating tables?
* do we have complete database schema specification?
* should we provide an ability to use existing pg transactions?

**Comment by nechaido** [comment] 2018-08-01 16:31
One more question: do we have a complete specification for JSQL?

**Comment by belochub** [comment] 2019-04-10 09:53
Duplicate of https://github.com/metarhia/globalstorage/issues/204.

**Closed by belochub** 2019-04-10 09:53 UTC
Labels: compatibility, functionality
